RobinNagpal/dodao-ai-agents

- crowd-fund-analysis/cf_analysis_agent/agent.py
- crowd-fund-analysis/cf_analysis_agent/utils/llm_utils.py
- crowd-fund-analysis/cf_analysis_agent/utils/process_project_utils.py
- crowd-fund-analysis/cf_analysis_agent/utils/report_utils.py
> add startup summary and fix all report generation

- crowd-fund-analysis/cf_analysis_agent/agent_state.py
- crowd-fund-analysis/cf_analysis_agent/app.py
- crowd-fund-analysis/cf_analysis_agent/structures/startup_metrics.py
- crowd-fund-analysis/cf_analysis_agent/utils/process_project_utils.py
- crowd-fund-analysis/cf_analysis_agent/utils/report_utils.py
> add repopulate endpoint

- crowd-fund-analysis/cf_analysis_agent/agent_state.py
- crowd-fund-analysis/cf_analysis_agent/reports/valuation.py
- crowd-fund-analysis/cf_analysis_agent/utils/process_project_utils.py
- crowd-fund-analysis/cf_analysis_agent/utils/report_utils.py
> fix valuation report

- crowd-fund-analysis/cf_analysis_agent/utils/process_project_utils.py
> fixed report generation

- crowd-fund-analysis/cf_analysis_agent/app.py
- crowd-fund-analysis/cf_analysis_agent/utils/process_project_utils.py
> add endpoint to regenerate specific report of al projects

- agent-tools/sec-edgar/src/lambda_function.py
- agent-tools/sec-edgar/src/test_local.py
- agent-tools/sec-edgar/test/test_aws.py
- langflow-bundles/custom_components/tools/sec-edgar-all-financials.py
- langflow-bundles/custom_components/tools/sec-edgar-report-type.py
> added new route

- crowd-fund-analysis/cf_analysis_agent/reports/financial_health.py
- crowd-fund-analysis/cf_analysis_agent/utils/process_project_utils.py
- langflow/README.md
> Add isntructions

- agent-tools/sec-edgar/requirements.txt
- agent-tools/sec-edgar/src/lambda_function.py
- agent-tools/sec-edgar/src/test_local.py
> added filtering and clean up code

- agent-tools/extract-from-reports/README.md
- agent-tools/extract-from-reports/attachments.py
- agent-tools/extract-from-reports/lambda_handler.py
- agent-tools/extract-from-reports/requirements.txt
- agent-tools/extract-from-reports/test.py
> working on extract lambda

- agent-tools/extract-criterion-info/README.md
- agent-tools/extract-criterion-info/lambda_handler.py
- agent-tools/sec-edgar/src/lambda_function.py
> added checklist of items to do

- docs/src/003_z01_generating_reports_reits.md
> added details of changes and steps

- agent-tools/extract-criterion-info/.gitignore
- agent-tools/extract-criterion-info/lambda_handler.py
- agent-tools/extract-criterion-info/requirements.txt
- agent-tools/extract-criterion-info/test_lambda_local.py
> Update matching logic

- langflow-bundles/custom_components/dodao_sec_tools/sec_edgar_10Q.py
> added initial code for all tools in single component

- agent-tools/agents-tools.json
- agent-tools/cdk/lib/agent-tools-stack.ts
- agent-tools/extract-criterion-info/.env.example
- agent-tools/extract-criterion-info/README.md
- agent-tools/extract-criterion-info/lambda_handler.py
> extract criteria tasks

- crowd-fund-analysis/cf_analysis_agent/api/public_equity_api.py
- crowd-fund-analysis/cf_analysis_agent/structures/criteria_structures.py
- crowd-fund-analysis/cf_analysis_agent/utils/get_criteria.py
- crowd-fund-analysis/cf_analysis_agent/utils/s3_utils.py
> added logic for updatinf custom-criterias and add ai criteria

- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/public_equity_structures.py
- koala-gains-backend/koala_gains/api/public_equity_api.py
- koala-gains-backend/koala_gains/structures/public_equity_structures.py
- koala-gains-backend/koala_gains/utils/criteria_utils.py
- koala-gains-backend/setup-files/latest-10q-report.json
> added logic for save and edit the criteria

- agent-tools/sec-edgar/Makefile
- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/public_equity_structures.py
- agent-tools/sec-edgar/src/test_local.py
- koala-gains-backend/setup-files/latest-10q-report.json
> Criteria lambda bug fixes

- langflow-bundles/custom_components/dodao_sec_tools/simple_api_request.py
> added code for simple api request component

- koala-gains-backend/koala_gains/api/public_equity_api.py
- koala-gains-backend/koala_gains/utils/ticker_utils.py
> change in validation to handle list input as well

- agent-tools/sec-edgar/src/public_equity_structures.py
> update the structures

- tasks/stock_types_tasks.md
> added documentation and checklist

- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/public_equity_structures.py
> changed prompt a bit

- agent-tools/sec-edgar/src/all_financial_reports.py
- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/public_equity_structures.py
- agent-tools/sec-edgar/src/ten_q/ten_q_content.py
- agent-tools/sec-edgar/src/test_file.py
- agent-tools/sec-edgar/src/test_local.py
- langflow-bundles/custom_components/dodao_sec_tools/simple_api_request.py
> sec edgar tool fixes

- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/test_local.py
> fix json serializable error

- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/public_equity_structures.py
> html to markdown conversion

- agent-tools/sec-edgar/src/app.py
- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/test_local.py
> created route for reporting period and filing link

- agent-tools/sec-edgar/src/criteria_matching.py
- koala-gains-backend/koala_gains/utils/criteria_matching.py
- langflow-bundles/custom_components/dodao_sec_tools/prompt_invocation.py
> prompt tool

- langflow-bundles/custom_components/dodao_sec_tools/custom_webhook.py
- langflow-bundles/custom_components/dodao_sec_tools/prompt_invocation.py
- langflow-bundles/custom_components/dodao_sec_tools/sec_edgar_10Q.py
> custom webhook langflow component

- langflow-bundles/custom_components/dodao_sec_tools/custom_webhook.py
> update custom webhook component name

- agent-tools/sec-edgar/.env.example
- agent-tools/sec-edgar/src/app.py
- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/test_local.py
- langflow-bundles/custom_components/dodao_sec_tools/get_price.py
- langflow-bundles/custom_components/dodao_sec_tools/prompt_invocation.py
> price component

- langflow-bundles/custom_components/dodao_sec_tools/get_price.py
> cast price to string

- langflow-bundles/custom_components/dodao_sec_tools/prompt_invocation.py
> remove memoization

- agent-tools/sec-edgar/src/all_financial_reports.py
- agent-tools/sec-edgar/src/app.py
- agent-tools/sec-edgar/src/criteria_matching.py
- agent-tools/sec-edgar/src/test_local.py
- koala-gains-backend/koala_gains/utils/criteria_matching.py
> change model

- agent-tools/sec-edgar/src/all_financial_reports.py
- agent-tools/sec-edgar/src/reports_search_map.py
- agent-tools/sec-edgar/src/specific_10Q_report.py
- agent-tools/sec-edgar/src/test_local.py
> fix data related to income statement
